name: Generate Node.js Packages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn --immutable
      - run: yarn run generate
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
