name: Generate Node.js Packages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: cprecioso/action-prepare-node@v1
      - run: yarn run generate
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
